name: singularity
on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

jobs:
  singularity:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-18.04'
        arch:
          - 'x64'
    steps:
      - run: wget -O- http://neuro.debian.net/lists/bionic.us-nh.full | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
      - run: sudo apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
      - run: sudo apt-get update
      - run: sudo apt-get install -y singularity-container
      - run: which -a singularity
      - run: singularity --version
      
